### ISSUE TITLE
Use Relational Pouch with requirejs

### ISSUE THREAD

**Issue by Iomegan** [pouchdb-community/relational-pouch#17]
Hi,

I am new to PouchDB and requirejs and would like to use Relational Pouch with requirejs. Unfortunately I always get the error: 'Uncaught TypeError: undefined is not a function' as soon as I want to use a relational pouch function. Looks like relational pouch is not not accessible, although it is is being loaded.

Here is my code: https://github.com/Iomegan/Pouchpouchdb-plugin-requirejsD/blob/master/scripts/client.js (and a test project)

Does Relational Pouch even work with requirejs? PouchDB alone works fine with.

**Comment by wishabhilash** [comment]
Am using requirejs and I can't understand the above snippet... :-/

Help please.

**Comment by calvinmetcalf** [comment]
@wishabhilash  does this make sense ?

```js
define(['pouchdb', 'relational-pouch'], function (PouchDB, relationalPouch){
    PouchDB.plugin(relationalPouch);
});
```

**Comment by wishabhilash** [comment]
@calvinmetcalf Thanks for the code. However, I have no idea where to put it.

I have put in requirejs config path:
```
'pouchdb': path/to/pouchdb,
'pouchdb_find': path/to/pouchdb_find
```
In shim:
```
pouchdb_find: {
    deps: ['pouchdb'],
    exports: 'pouchdb_find',
}
```

The following are the things I tried:
 - Created another file with the above code and called it in config require. pouchdb_find came out to be undefined.
- Tried it writing inside 'init' of shim. Same thing.

Kindly explain it in a bit a detail so that once and for all it be solved for everyone. I would also update these info on some blog so that people get the help.

Thank you. :)

**Comment by nolanlawson** [comment]
I've been told that the only way to get my plugins to run in RequireJS is to build them in the Browserify "standalone" style. Luckily wzrd.in will do that for you: http://wzrd.in/standalone/relational-pouch@latest

In this case, you would just need to use whatever RequireJS mechanism you would use for importing a "global" script into RequireJS, since both of them export globals `window.PouchDB` for the first script, `window.relationalPouch` for the second script.

**Comment by brachycera** [comment]
@wishabhilash this is my requireJS setup to load pouchDB

    require.config ({
         paths   : {
                'PouchDb'           : 'bower_components/pouchdb/dist/pouchdb',
                'database'          : 'database'
         }
     });

    (function ( define ) {
    'use strict';
    define( ['PouchDb'],
        function ( PouchDb ) {
            var Database = function ( ) {

                var db = new PouchDb('local_database');

                return {
                    allDocs: function ( options ) {
                        return db.allDocs( options );
                    },
                    get: function ( id ) {
                        return db.get( id );
                    },
                    save: function ( obj ) {
                        return db.put( obj );
                    },
                    delete: function ( obj ) {
                        return db.remove( obj );
                    },
                    bulk: function ( obj ){
                        return db.bulkDocs( obj );
                    }
                };
            };
            return [ Database ];
        }
    );
    }( define ));

**Comment by wishabhilash** [comment]
Hi all, it seems I might have forgotten to post my reply, so thanks to @brachycera to revive this thread again.

@brachycera I think your approach rather limits the full power of PouchDB. So to all the requirejs users the following snippet would help you to setup PouchDB for requirejs.

* Follow @nolanlawson comment above to browserify the PouchDB and the PouchDB plugins (if you need any).
* Refer to then in requirejs config file.
```
require.config ({
     paths   : {
            pouchdb: './path/to/pouchdb.min',
            pouchdb_find: './path/to/pouchdb.find.min',
            pouchdb_erase: './path/to/pouchdb.erase.min',
     }
 });
```
* Create another file pouchdbPluginLoader.js and put the following content in it.
```
define(['pouchdb', 'pouchdb_find', 'pouchdb_erase'], function(PouchDB, pouchdb_find, pouchdb_erase){
	PouchDB.plugin(pouchdb_find);
	PouchDB.plugin(pouchdb_erase);
})
```
* Use the following construct in require functions to refer to plugin loader. (this needs to be called only once, so this can be called in the entry point require function, in rest of the define functions pouchdb, pouchdb_find and pouchdb_erase needs to be called as per convention)
```
require([
	...
	'./app/constructs/pouchPluginLoader',
], function(...){
	...
})
```

I hope this helps all the requirejs users. :)
